<?php

namespace ContainerMsGnnVf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPost2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Bnq4aHZ.App\Entity\Post' shared service.
     *
     * @return \App\Entity\Post
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Bnq4aHZ": it references class "App\\Entity\\Post" but no such service exists.');
    }
}
