version: '2.1'

services:
    elastic-apm-php-component-tests-mysql:
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_DATABASE=${ELASTIC_APM_PHP_TESTS_MYSQL_DB}
            - MYSQL_ROOT_PASSWORD=${ELASTIC_APM_PHP_TESTS_MYSQL_PASSWORD}
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: [ "CMD", "mysqladmin", "--host=localhost", "--user=${ELASTIC_APM_PHP_TESTS_MYSQL_USER}", "--password=${ELASTIC_APM_PHP_TESTS_MYSQL_PASSWORD}", "ping" ]
            timeout: 5s
            retries: 60
        networks:
            - elastic-apm-php-external-services-for-component-tests-net

    elastic-apm-php-component-tests-wait-for-all-services-to-start:
        image: busybox
        depends_on:
            elastic-apm-php-component-tests-mysql:
                condition: service_healthy

networks:
    elastic-apm-php-external-services-for-component-tests-net:
        name: elastic-apm-php-external-services-for-component-tests-net
        driver: bridge
