#!/usr/bin/env groovy

@Library('apm@current') _

pipeline {
  agent { label 'linux && immutable' }
  environment {
    REPO = 'apm-agent-php'
    BASE_DIR = "src/go.elastic.co/apm/${env.REPO}"
    NOTIFY_TO = credentials('notify-to')
    JOB_GCS_BUCKET = credentials('gcs-bucket')
  }
  options {
    timeout(time: 1, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20', daysToKeepStr: '30'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
    rateLimitBuilds(throttle: [count: 60, durationName: 'hour', userBoost: true])
    quietPeriod(10)
  }
  triggers {
    issueCommentTrigger('(?i).*jenkins\\W+run\\W+(?:the\\W+)?tests(?:\\W+please)?.*')
  }
  stages {
    /**
    Cancel all the previous running old builds for the current PR.
    */
    stage('Cancel old builds') {
      when { changeRequest() }
      options { skipDefaultCheckout() }
      steps {
        cancelPreviousRunningBuilds()
      }
    }
    stage('Checkout') {
      options { skipDefaultCheckout() }
      steps {
        deleteDir()
        gitCheckout(basedir: "${BASE_DIR}", githubNotifyFirstTimeContributor: true)
        stash allowEmpty: true, name: 'source', useDefaultExcludes: false
      }
    }
    stage('Build') {
      options { skipDefaultCheckout() }
      steps {
        withGithubNotify(context: 'Build') {
          deleteDir()
          unstash 'source'
          dir("${BASE_DIR}"){
            sh script: 'docker build --tag apm-agent-php .', label: 'prepare docker image'
            sh script: 'docker run --rm -u $(id -u):$(id -g) -t -v $(pwd):/app apm-agent-php', label: 'run build'
          }
        }
      }
    }
    stage('Test') {
      options { skipDefaultCheckout() }
      steps {
        withGithubNotify(context: 'Test', tab: 'tests') {
          dir("${BASE_DIR}"){
            sh script: 'docker run --rm -u $(id -u):$(id -g) -t -v $(pwd):/app apm-agent-php make test', label: 'run tests'
          }
        }
      }
      post {
        always {
          junit(allowEmptyResults: true, keepLongStdio: true, testResults: "${BASE_DIR}/junit.xml")
        }
      }
    }
    stage('Install') {
      options { skipDefaultCheckout() }
      steps {
        withGithubNotify(context: 'Install') {
          dir("${BASE_DIR}"){
            sh script: 'docker run --rm -u $(id -u):$(id -g) -t -v $(pwd):/app apm-agent-php make install', label: 'run install'
          }
        }
      }
    }
  }
  post {
    cleanup {
      notifyBuildResult()
    }
  }
}
