<?php

namespace ContainerJaiVJpe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddUserCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\AddUserCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\AddUserCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:add-user', [], 'Creates users and stores them in the database', false, #[\Closure(name: 'App\\Command\\AddUserCommand')] function () use ($container): \App\Command\AddUserCommand {
            return ($container->privates['App\\Command\\AddUserCommand'] ?? $container->load('getAddUserCommandService'));
        });
    }
}
