<?php

namespace ContainerJaiVJpe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagsInputTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\TagsInputType' shared autowired service.
     *
     * @return \App\Form\Type\TagsInputType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/TagsInputType.php';

        return $container->privates['App\\Form\\Type\\TagsInputType'] = new \App\Form\Type\TagsInputType(($container->privates['App\\Repository\\TagRepository'] ?? $container->load('getTagRepositoryService')));
    }
}
