FROM nginx:latest

COPY . /var/www

WORKDIR /var/www
RUN chmod -R 777 docker/mysql/
#RUN curl -fsSL https://github.com/elastic/apm-agent-php/releases/download/v1.5/apm-agent-php_1.5_all.deb > /tmp/apm-gent-php.deb \
#    && dpkg -i /tmp/apm-gent-php.deb