version: '2.1'

services:
    wordpress:
        depends_on:
            db:
                condition: service_healthy
        build:
            context: .
            args:
                WORDPRESS_DOCKER_LABEL: "${WORDPRESS_DOCKER_LABEL:-6.1.0-php8.1-fpm}"
                PHP_AGENT_INSTALL_LOCAL_EXTENSION_BINARY: "${PHP_AGENT_INSTALL_LOCAL_EXTENSION_BINARY:-}"
                PHP_AGENT_INSTALL_PACKAGE_FROM_URL: "${PHP_AGENT_INSTALL_PACKAGE_FROM_URL:-}"
                PHP_AGENT_INSTALL_RELEASE_VERSION: "${PHP_AGENT_INSTALL_RELEASE_VERSION:-}"
        environment:
            ELASTIC_APM_SERVICE_NAME: ${ELASTIC_APM_SERVICE_NAME:-Wordpress-demo-app}
            ELASTIC_APM_ENVIRONMENT: ${ELASTIC_APM_ENVIRONMENT:-demo}
            ELASTIC_APM_SERVER_URL: ${ELASTIC_APM_SERVER_URL:-http://apm-server:8200}
            ELASTIC_APM_LOG_LEVEL:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        volumes:
            - ./_TEMP/shared_wordpress_var_www_html:/var/www/html

    nginx:
        image: nginx:latest
        depends_on:
            - wordpress
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./_TEMP/shared_wordpress_var_www_html:/var/www/html
        ports:
            - "${WEB_FRONT_HOST:-127.0.0.1}:8080:80"
        healthcheck:
            test: ["CMD", "curl", "--max-time", "10", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://localhost:80/"]
            retries: 10
            interval: 10s

    db:
        image: mysql:${MYSQL_VERSION:-5.7}
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        healthcheck:
            test: [ "CMD", "mysqladmin", "--host=localhost" ,"ping" ]
            timeout: 20s
            retries: 10

    wait_for_all_services_to_be_healthy:
        image: busybox
        depends_on:
            nginx:
                condition: service_healthy
