:toc: macro
:toc-title:
:toclevels: 4

[[public-api]]
== Public API
The public API of the Elastic APM PHP agent lets you
customize and manually create spans and transactions.

toc::[]

[float]
[[api-elasticapm]]
=== ElasticApm
This is the entry point of the public API.
It allows to start transactions, gives you access to the current transaction, etc.

To use the API, you invoke the static methods on the class `\Elastic\Apm\ElasticApm`.

[float]
[[api-elasticapm-begin-current-transaction]]
==== Begin a new transaction and set it as the current one
Begins a new transaction and sets it as the current transaction.
Use this method to create a custom transaction.
Note that when automatic instrumentation is used
the agent begins a new transaction automatically
whenever your application receives an incoming HTTP request
so you only need to use this method to create custom transactions.

NOTE: You must call <<api-transaction-end,`end()`>> when the transaction has ended.

The best practice is to use a `try`-`finally` block.
For example:

[source,php]
----
use Elastic\Apm\ElasticApm;

$transaction = ElasticApm::beginCurrentTransaction(
    'transaction_name',
    'transaction_type'
);
try {
    // do your thing ...
} finally {
    $transaction->end();
}
----

See <<api-transaction>> on how to customize a transaction.

[float]
[[api-elasticapm-capture-current-transaction]]
==== Capture a new transaction and set it as the current one
This is a convenience API that ensures <<api-transaction-end,`end()`>> is called
when the transaction has ended.
This API:

* Begins a new transaction
* Sets the new transaction as the current transaction
* Executes the provided `callable` as the new transaction
* Ends the new transaction
* Returns the value returned by the provided `callable`

For example:

[source,php]
----
use Elastic\Apm\ElasticApm;

ElasticApm::captureCurrentTransaction(
    'transaction_name',
    'transaction_type'
    function (TransactionInterface $transaction) {
        // do your thing...
    }
);
----

See <<api-transaction>> on how to customize a transaction.

[float]
[[api-elasticapm-get-current-transaction]]
==== Get the current transaction
Returns the current transaction.

[source,php]
----
use Elastic\Apm\ElasticApm;

$transaction = ElasticApm::getCurrentTransaction();
----

See <<api-transaction>> on how to customize a transaction.

[float]
[[api-transaction]]
=== Transaction interface
A transaction describes an event captured by an Elastic APM agent monitoring a service.
Transactions help combine multiple <<api-span,Spans>> into logical groups,
and they are the first <<api-span,Span>> of a service.
More information on Transactions and Spans is available
in the {apm-overview-ref-v}/apm-data-model.html[APM data model] documentation.

See <<api-elasticapm-get-current-transaction>> on how to get a reference to the current transaction.

[float]
[[api-transaction-get-current-span]]
==== Get the current span
Returns the current span for this transaction.

Example:
[source,php]
----
$span = $transaction->getCurrentSpan();
----

[float]
[[api-transaction-begin-current-span]]
==== Begin a new span and set it as the current one
Begins a new span with the current span as the new span's parent and
sets the new span as the current span for this transaction.
If this transaction's doesn't have the current span
then the transaction itself is set as the new span's parent.

NOTE: You must call <<api-span-end,`end()`>> when the span has ended.

The best practice is to use a `try`-`finally` block.
For example:

[source,php]
----
$span = $transaction->beginCurrentSpan(
    'span_name',
    'span_type',
    'span_sub-type', // optional
    'span_action' // optional
);
try {
    // do your thing ...
} finally {
    $span->end();
}
----

[float]
[[api-transaction-capture-current-span]]
==== Capture a new span and set it as the current one
This is a convenience API that ensures <<api-span-end,`end()`>> is called
when the span has ended.
This API

* Begins a new span with this transaction's current span as the new span's parent and
    sets the new span as the current span for this transaction.
    If this transaction's doesn't have a current span
    then the transaction itself is set as the new span's parent.
* Executes the provided `callable` as the new span
* Ends the new transaction
* Returns the value returned by the provided `callable`

For example:

[source,php]
----
$transaction->captureCurrentSpan(
    'span_name',
    'span_type'
    function (SpanInterface $childSpan) {
        // do your thing...
    },
    'span_sub-type', // optional
    'span_action' // optional
);
----

[float]
[[api-transaction-begin-child-span]]
==== Begin a new span as transaction's direct child
Begins a new span with this transaction as the new span's parent.

NOTE: You must call <<api-span-end,`end()`>> when the span has ended.

The best practice is to use `try`-`finally` block.
For example:

[source,php]
----
$span = $transaction->beginChildSpan(
    'span_name',
    'span_type',
    'span_sub-type', // optional
    'span_action' // optional
);
try {
    // do your thing ...
} finally {
    $span->end();
}
----

[float]
[[api-transaction-capture-child-span]]
==== Capture a new span as transaction's direct child
This is a convenience API that ensures <<api-span-end,`end()`>> is called
when the span has ended.
This API

* Begins a new span with this transaction as the new span's parent
* Executes the provided `callable` as the new span and
* Ends the new span
* Returns the value returned by the provided `callable`

For example:

[source,php]
----
$transaction->captureChildSpan(
    'span_name',
    'span_type'
    function (SpanInterface $span) {
        // do your thing...
    },
    'span_sub-type', // optional
    'span_action' // optional
);
----

[float]
[[api-transaction-set-name]]
==== Set transaction name
Sets the name of the transaction.
Transaction name is generic designation of a transaction in the scope of a single service (e.g., `GET /users/:id`).

Example:
[source,php]
----
$transaction->setName('GET /users/:id');
----

[float]
[[api-transaction-get-name]]
==== Get transaction name
Gets the name of the transaction.

Example:
[source,php]
----
$transactionName = $transaction->getName();
----

[float]
[[api-transaction-set-type]]
==== Set transaction type
Sets the type of the transaction.
Transaction type is a keyword of specific relevance in the service's domain.
For example `request`, `backgroundjob`, etc.

Example:
[source,php]
----
$transaction->setType('my custom transaction type');
----

[float]
[[api-transaction-get-type]]
==== Get transaction type
Gets the type of the transaction.

Example:
[source,php]
----
$transactionType = $transaction->getType();
----

[float]
[[api-transaction-set-label]]
==== Add a label to transaction
Sets a label by a key.
Labels are a flat mapping of user-defined string keys and string, number, or boolean values.

NOTE: The labels are indexed in Elasticsearch so that they are searchable and aggregatable.
Take special care when using user provided data, like URL parameters,
as a label key because it can lead to {ref}/mapping.html#mapping-limit-settings[Elasticsearch mapping explosion].

Example:
[source,php]
----
$transaction->context()->setLabel('my label with string value', 'some text');
$transaction->context()->setLabel('my label with int value', 123);
$transaction->context()->setLabel('my label with float value', 4.56);
----

[float]
[[api-transaction-get-id]]
==== Get transaction ID
Gets the ID of the transaction.
Transaction ID is a hex encoded 64 random bits (== 8 bytes == 16 hex digits) ID.

If this transaction represents a noop, this method returns an unspecified dummy ID.

Example:
[source,php]
----
$transactionId = $transaction->getId();
----

[float]
[[api-transaction-get-trace-id]]
==== Get transaction trace-ID
Gets the trace ID of the transaction.
Trace ID is a hex encoded 128 random bits (== 16 bytes == 32 hex digits) ID of the correlated trace.

The trace ID is consistent across all transactions and spans which belong to the same logical trace,
even for transactions and spans which happened in another service
(given this service is also monitored by Elastic APM).

If this transaction represents a noop, this method returns an unspecified dummy ID.

Example:
[source,php]
----
$traceId = $transaction->getTraceId();
----

[float]
[[api-transaction-get-parent-id]]
==== Get transaction parent-ID
Gets ID of the parent transaction or span.

See <<api-transaction-get-id>> and <<api-span-get-id>>.

The root transaction of a trace does not have a parent, so `null` is returned.

If this transaction represents a noop, this method returns an unspecified dummy ID.

Example:
[source,php]
----
$parentId = $transaction->getParentId();
----

[float]
[[api-transaction-end]]
==== End transaction
Ends the transaction and queues it to be reported to the APM Server.

It is illegal to call any mutating methods (i.e., not `getXyz`) on a transaction instance which has already ended.

Example:

[source,php]
----
$transaction->end();
----

[float]
[[api-span]]
=== Span interface
A span contains information about a specific code path, executed as part of a transaction.

If for example a database query happens within a recorded transaction,
a span representing this database query may be created.
In such a case the name of the span will contain information about the query itself,
and the type will hold information about the database type.

See <<api-transaction-get-current-span>> on how to get the current span.

[float]
[[api-span-set-name]]
==== Set span name
Sets the name of the span.
Span name is generic designation of a span in the scope of a transaction.

Example:
[source,php]
----
$span->setName('SELECT FROM customer');
----

[float]
[[api-span-get-name]]
==== Get span name
Gets the name of the span.

Example:
[source,php]
----
$spanName = $span->getName();
----

[float]
[[api-span-set-type]]
==== Set span type
Sets the type of the span.
Span type is a keyword of specific relevance in the service's domain.
For example `db`, `external`, etc.

Example:
[source,php]
----
$span->setType('my custom span type');
----

[float]
[[api-span-get-type]]
==== Get span type
Gets the type of the span.

Example:
[source,php]
----
$spanType = $span->getType();
----

[float]
[[api-span-set-subtype]]
==== Set span sub-type
Sets the sub-type of the span.
Span sub-type is a further sub-division of the type.
For example, `mysql`, `postgresql`, or `elasticsearch` for the type `db`, `http` for the type `external`, etc.

Span sub-type is optional and can be set to `null`.
Span sub-type default value is `null`.

Example:
[source,php]
----
$span->setSubtype('my custom span sub-type');
----

[float]
[[api-span-get-subtype]]
==== Get span sub-type
Gets the sub-type of the span.

Example:
[source,php]
----
$spanSubtype = $span->getSubtype();
----

[float]
[[api-span-set-action]]
==== Set span action
Sets the action of the span.
Span action is the specific kind of event within the sub-type represented by the span.
For example `query` for type/sub-type `db`/`mysql`, `connect` for type/sub-type `db`/`cassandra`, etc.

Span action is optional and can be set to `null`.
Span action default value is `null`.

Example:
[source,php]
----
$span->setAction('my custom span action');
----

[float]
[[api-span-get-action]]
==== Get span action
Gets the action of the span.

Example:
[source,php]
----
$spanAction = $span->getAction();
----

[float]
[[api-span-set-label]]
==== Add a label to span
Sets a label by a key.
Labels are a flat mapping of user-defined string keys and string, number, or boolean values.

NOTE: The labels are indexed in Elasticsearch so that they are searchable and aggregatable.
Take special care when using user provided data, like URL parameters,
as a label key because it can lead to {ref}/mapping.html#mapping-limit-settings[Elasticsearch mapping explosion].

Example:
[source,php]
----
$span->context()->setLabel('my label with string value', 'some text');
$span->context()->setLabel('my label with int value', 123);
$span->context()->setLabel('my label with float value', 4.56);
----

[float]
[[api-span-get-id]]
==== Get span ID
Gets the ID of the span.
Span ID is a hex encoded 64 random bits (== 8 bytes == 16 hex digits) ID.

If this span represents a noop, this method returns an unspecified dummy ID.

Example:
[source,php]
----
$spanId = $span->getId();
----

[float]
[[api-span-get-trace-id]]
==== Get span trace-ID
Gets the trace ID of the span.
Trace ID is a hex encoded 128 random bits (== 16 bytes == 32 hex digits) ID of the correlated trace.

The trace ID is consistent across all transactions and spans which belong to the same logical trace,
even for transactions and spans which happened in another service
(given this service is also monitored by Elastic APM).

If this span represents a noop, this method returns an unspecified dummy ID.

Example:
[source,php]
----
$traceId = $span->getTraceId();
----

[float]
[[api-span-get-transaction-id]]
==== Get span transaction-ID
Gets ID of the correlated transaction.
See <<api-transaction-get-id>>.

If this span represents a noop, this method returns an unspecified dummy ID.

Example:
[source,php]
----
$transactionId = $span->getTransactionId();
----

[float]
[[api-span-get-parent-id]]
==== Get span parent-ID
Gets ID of the parent transaction or span.
If this span is a direct child of the correlated transaction then its parent is the correlated transaction,
otherwise, its parent is the parent span.
See <<api-transaction-get-id>> and <<api-span-get-id>>.

If this span represents a noop, this method returns an unspecified dummy ID.

Example:
[source,php]
----
$parentId = $span->getParentId();
----

[float]
[[api-span-begin-child-span]]
==== Begin a new span as this span's direct child
Begins a new span with this span as the new span's parent.

NOTE: You must call <<api-span-end,`end()`>> when the span has ended.

The best practice is to use a `try`-`finally` block.
For example:

[source,php]
----
$childSpan = $parentSpan->beginChildSpan(
    'span_name',
    'span_type',
    'span_sub-type', // optional
    'span_action' // optional
);
try {
    // do your thing ...
} finally {
    $childSpan->end();
}
----

[float]
[[api-span-capture-child-span]]
==== Capture a new span as this span's direct child
This is a convenience API that ensures <<api-span-end,`end()`>> is called
when the span has ended.
This API

* Begins a new span with this span as the new span's parent
* Executes the provided `callable` as the new span
* Ends the new span
* Returns the value returned by the provided `callable`

For example:

[source,php]
----
$parentSpan->captureChildSpan(
    'span_name',
    'span_type'
    function (SpanInterface $childSpan) {
        // do your thing...
    },
    'span_sub-type', // optional
    'span_action' // optional
);
----

[float]
[[api-span-end]]
==== End span
Ends the span and queues it to be reported to the APM Server.

It is illegal to call any mutating methods (i.e., not `getXyz`) on a span instance which has already ended.

Example:
[source,php]
----
$span->end();
----
