ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/php[elastic.co]
endif::[]

[[setup]]
== Set up the Agent

Install the agent using one of the https://github.com/elastic/apm-agent-php/releases/latest[packages for supported platforms].

NOTE: The agent supports PHP versions 7.2-7.4.

=== Using RPM package (RHEL/CentOS, Fedora)
[source,bash]
----
rpm -ivh <package-file>.rpm
----

=== Using DEB package (Debian, Ubuntu)
[source,bash]
----
dpkg -i <package-file>.deb
----

=== Using APK package (Alpine)
[source,bash]
----
apk add --allow-untrusted <package-file>.apk
----

[[build_from-source]]
=== Build from source

If you can’t find your distribution, you can install the agent by building it from the source.

NOTE: The agent is currently only available for a unix-lke operating system.

1. Download the agent source from https://github.com/elastic/apm-agent-php/.
2. Execute the following commands to build the agent and install it:

[source,bash]
----
cd src/ext
phpize
CFLAGS="-std=gnu99" ./configure --enable-elastic_apm
make clean
make
sudo make install
----

Enable the extension by adding the following to your `php.ini` file:

[source,php]
----
extension=elastic_apm.so
elastic_apm.bootstrap_php_part_file=<repo root>/src/bootstrap_php_part.php
----

NOTE: In order to work the agent needs both the built `elastic_apm.so`
and the downloaded source files.
So if you would like to build `elastic_apm.so` on one machine and
then deploy it on a different machine you will need to copy both
the built `elastic_apm.so` and the downloaded source files.
