ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/php[elastic.co]
endif::[]

[[setup]]
== Set up the Agent

[discrete]
[[setup-prerequisites]]
=== Prerequisites

[discrete]
==== Operating system
The agent is currently only available for the Linux operating system.

[discrete]
==== PHP
The agent supports PHP versions 7.2-8.2.

[discrete]
==== curl
The agent requires `libcurl` 7.58 or later.

[discrete]
[[setup-installation]]
=== Installation

Install the agent using one of the https://github.com/elastic/apm-agent-php/releases/latest[packages for supported platforms].

[discrete]
[[setup-rpm]]
==== Using RPM package (RHEL/CentOS, Fedora)

[source,bash]
----
rpm -ivh <package-file>.rpm
----

[discrete]
[[setup-deb]]
==== Using DEB package (Debian, Ubuntu 18+)

[source,bash]
----
dpkg -i <package-file>.deb
----

[discrete]
[[setup-apk]]
==== Using APK package (Alpine)

[source,bash]
----
apk add --allow-untrusted <package-file>.apk
----

[discrete]
[[build-from-source]]
==== Build from source

If you can’t find your distribution, you can install the agent by building it from the source.

NOTE: The agent is currently only available for Linux operating system.

1. Download the agent source from https://github.com/elastic/apm-agent-php/.
2. Execute the following commands to build the agent and install it:

[source,bash]
----
cd src/ext
phpize
CFLAGS="-std=gnu99" ./configure --enable-elastic_apm
make clean
make
sudo make install
----

Enable the extension by adding the following to your `php.ini` file:

[source,php]
----
extension=elastic_apm.so
elastic_apm.bootstrap_php_part_file=<repo root>/src/bootstrap_php_part.php
----

To work, the agent needs both the built `elastic_apm.so`
and the downloaded source files.
So if you would like to build `elastic_apm.so` on one machine and
then deploy it on a different machine, you will need to copy both
the built `elastic_apm.so` and the downloaded source files.
