ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/php[elastic.co]
endif::[]

[[setup]]
== Set up the Agent

[discrete]
[[setup-prerequisites]]
=== Prerequisites

[discrete]
==== Operating system
The agent is currently only available for the Linux operating system.

[discrete]
==== PHP
The agent supports PHP versions 7.2-8.2.

[discrete]
==== curl
The agent requires `libcurl` 7.58 or later.

[discrete]
[[setup-installation]]
=== Installation

Install the agent using one of the https://github.com/elastic/apm-agent-php/releases/latest[packages for supported platforms].

[discrete]
[[setup-rpm]]
==== Using RPM package (RHEL/CentOS, Fedora)

[source,bash]
----
rpm -ivh <package-file>.rpm
----

[discrete]
[[setup-deb]]
==== Using DEB package (Debian, Ubuntu 18+)

[source,bash]
----
dpkg -i <package-file>.deb
----

[discrete]
[[setup-apk]]
==== Using APK package (Alpine)

[source,bash]
----
apk add --allow-untrusted <package-file>.apk
----

[discrete]
[[build-from-source]]
==== Build from source

If you can’t find your distribution, you can install the agent by building it from the source.
The following instructions will build the APM agent using the same docker environment that Elastic uses to build our official packages.

NOTE: The agent is currently only available for Linux operating system.

1. Download the agent source from https://github.com/elastic/apm-agent-php/.
2. Execute the following commands to build the agent and install it:

[source,bash]
----
cd apm-agent-php
# for linux glibc - libc distributions (Ubuntu, Redhat, etc)
export BUILD_ARCHITECTURE=linux-x86-64
# for linux with musl - libc distributions (Alpine)
export BUILD_ARCHITECTURE=linuxmusl-x86-64
# provide a path to php-config tool
export PHP_CONFIG=php-config

# build extensions
make -f .ci/Makefile build

# run extension tests
PHP_VERSION=`$PHP_CONFIG --version | cut -d'.' -f 1,2` make -f .ci/Makefile run-phpt-tests

# install agent extensions
sudo cp agent/native/_build/${BUILD_ARCHITECTURE}-release/ext/elastic_apm-*.so `$PHP_CONFIG --extension-dir`

# install automatic loader
sudo cp agent/native/_build/${BUILD_ARCHITECTURE}-release/loader/code/elastic_apm_loader.so `$PHP_CONFIG --extension-dir`

----

Enable the extension by adding the following to your `php.ini` file:

[source,ini]
----
extension=elastic_apm_loader.so
elastic_apm.bootstrap_php_part_file=<repo root>/agent/php/bootstrap_php_part.php
----

To work, the agent needs both the built `elastic_apm-*.so`
and the downloaded source files.
So if you would like to build `elastic_apm-*.so` on one machine and
then deploy it on a different machine, you will need to copy both
the built `elastic_apm-*.so` and the downloaded source files.

[discrete]
[[limitations]]
=== Limitations

[discrete]
[[limitation-open_basedir]]
==== `open_basedir` PHP configuration option
Please be aware that if the https://www.php.net/manual/en/ini.core.php#ini.open-basedir[`open_basedir`]
option is configured in your php.ini,
the installation directory of the agent (by default `/opt/elastic/apm-agent-php`)
must be located within a path included in the
https://www.php.net/manual/en/ini.core.php#ini.open-basedir[`open_basedir`] value.
Otherwise, the agent will not be loaded correctly.
