FROM arm64v8/ubuntu:18.04 as devtools

ARG GCC_VERSION=12.2.0
ARG BINUTILS_VERSION=2.40
ARG CMAKE_VERSION=3.26.3
ARG PYTHON_VERSION=3.9.16
ARG USER_NAME=build

#binutils: bison - gprofng, texinfo - makeinfo

RUN apt-get update && apt-get -y install sudo curl wget git make autoconf bzip2 \
    texinfo bison \
    python3 python3-pip python3-venv \
    binutils gcc libz-dev

RUN adduser --disabled-password --gecos "" ${USER_NAME} \
    && echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers

USER ${USER_NAME}

RUN mkdir -p /home/${USER_NAME}/prerequisities
WORKDIR /home/${USER_NAME}/prerequisities

RUN curl -LO https://gcc.gnu.org/pub/gcc/releases/gcc-${GCC_VERSION}/gcc-${GCC_VERSION}.tar.xz \
 && tar -xf gcc-${GCC_VERSION}.tar.xz \
 && rm gcc-${GCC_VERSION}.tar.xz

RUN cd gcc-${GCC_VERSION} \
 && ./contrib/download_prerequisites \
 && CFG_OPTIONS="--enable-languages=c,c++ --enable-shared --enable-linker-build-id --with-system-zlib --without-included-gettext --enable-threads=posix --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --disable-werror --enable-checking=release --with-pic --disable-symvers --enable-obsolete \
 --disable-libstdcxx-visibility --enable-libstdcxx-debug-flags=-gdwarf-2 --disable-multilib \ 
 --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu" \
 && echo $CFG_OPTIONS \
 && ./configure --prefix=/opt/gcc-${GCC_VERSION} $CFG_OPTIONS \
 && make -j$(nproc) \
 && sudo make install \
 && cd - \
 && rm -rf gcc-${GCC_VERSION}

RUN curl -LO https://ftp.gnu.org/gnu/binutils/binutils-${BINUTILS_VERSION}.tar.xz \
 && tar -xf binutils-${BINUTILS_VERSION}.tar.xz \
 && rm binutils-${BINUTILS_VERSION}.tar.xz 

RUN cd binutils-${BINUTILS_VERSION} \
 && ./configure --prefix=/opt/binutils-${BINUTILS_VERSION} CFLAGS=-Wno-unused-value --enable-gold \
 && make -j$(nproc) \
 && sudo make install \
 && cd - \
 && rm -rf binutils-${BINUTILS_VERSION}

RUN curl -OL https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-aarch64.sh \
 && chmod +x cmake-${CMAKE_VERSION}-linux-aarch64.sh \
 && sudo mkdir -p /opt/cmake-${CMAKE_VERSION} \
 && sudo ./cmake-${CMAKE_VERSION}-linux-aarch64.sh --skip-license --prefix=/opt/cmake-${CMAKE_VERSION} \
 && rm cmake-${CMAKE_VERSION}-linux-aarch64.sh

RUN curl -LO https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz \
 && tar -xf Python-${PYTHON_VERSION}.tgz \
 && rm Python-${PYTHON_VERSION}.tgz

#RUN sudo apt-get -y install libffi-dev openssl-dev sqlite-dev readline-dev xz-dev bzip2-dev

RUN cd Python-${PYTHON_VERSION} \
 && ./configure --help \
 && ./configure --enable-optimizations --prefix=/opt/python-${PYTHON_VERSION} \
 && make \
 && sudo make install

RUN sudo apt-get clean


FROM arm64v8/ubuntu:18.04

ARG GCC_VERSION=12.2.0
ARG BINUTILS_VERSION=2.40
ARG CMAKE_VERSION=3.26.3
ARG PYTHON_VERSION=3.9.16
ARG USER_NAME=build

COPY --from=devtools /opt /opt

RUN apt-get -y update && apt-get -y install sudo curl wget git make autoconf bzip2 file libc-dev

RUN adduser --disabled-password --gecos "" ${USER_NAME} \
    && echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers

USER ${USER_NAME}

ENV PATH="/opt/binutils-${BINUTILS_VERSION}/bin:/opt/cmake-${CMAKE_VERSION}/bin:/opt/python-${PYTHON_VERSION}/bin:${PATH}"
ENV CMAKE_INSTALL_PREFIX=/opt/cmake-${CMAKE_VERSION}
